### ISSUE TITLE
Err: The trajectory of ped with ID <1> is not continuous. Please modify the trajectory file!

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpsreport#133]
In Gitlab by @AKRay93 on Jun 19, 2019, 13:32 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpsreport/issues/110)]

## Summary
Windows 10, PowerShell

```
. ..\..\bin\jpsreport.exe ini_corridor_december.xml
```

JPSreport does not finish the analysis because "The trajectory of ped with ID <1> is not continuous.". The same error occurs for all IDs. 
The error does not occur for a trajectory file from the demo folder of JuPedSim with the same inifile and geometry file.

## Inifile, Geometry file, Trajectory file
[ini_corridor_december.xml](https://gitlab.version.fz-juelich.de/JuPedSim/jpsreport/uploads/ba6f5dcf274ddc5466595bfdbb6df402/ini_corridor_december.xml)
[geo_test2.xml](/uploads/b3d311bb90d6219d91e64be47afa9abf/geo_test2.xml)
[traj_100_N25_h0_R2.txt](/uploads/5d3ee46f598dd95213b757c7f8dd38a5/traj_100_N25_h0_R2.txt)

## Screenshot
![PowerShell_JPSreport_DecemberExp](/uploads/796aeae07dd794f05560b15810ce58ae/PowerShell_JPSreport_DecemberExp.jpg)

**Comment by chraibi** [comment]
In Gitlab by @AKRay93 on Jun 19, 2019, 13:32

changed the description

**Comment by chraibi** [comment]
In Gitlab by @AKRay93 on Jun 19, 2019, 13:36

changed the description

**Comment by chraibi** [comment]
In Gitlab by @AKRay93 on Jun 19, 2019, 13:39

changed the description

**Comment by chraibi** [comment]
In Gitlab by @AKRay93 on Jun 19, 2019, 13:51

If I leave out some things in the header of the file and use this trajectory file
[traj_100_N25_h0_R2_test.txt](https://gitlab.version.fz-juelich.de/JuPedSim/jpsreport/uploads/b63b62c13b3bf032df44c3581d295d17/traj_100_N25_h0_R2_test.txt)
it doesn't produce the error (see Screenshot 2) but still doesn't produce any output.

Screenshot 2: ![PowerShell_JPSreport_DecemberExp2](/uploads/1671d404f2bd176b71fe225c6736c6cc/PowerShell_JPSreport_DecemberExp2.jpg)

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 19, 2019, 14:22

changed the description

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 19, 2019, 14:52

Kathi, could be you are using an old version? 

Please show a screenshot like this (just type `jpsreport` without inifile)

![](https://www.dropbox.com/s/wbgsfiv2nete1b7/Screenshot%202019-06-19%2014.45.45.png?dl=1)

For me, the analysis works fine. Here is the log. [log.txt](https://gitlab.version.fz-juelich.de/JuPedSim/jpsreport/uploads/30939c5f5ff07d56e0f164a61dbf7122/log.txt)

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 19, 2019, 15:00

assigned to @gjaeger

**Comment by chraibi** [comment]
In Gitlab by @gjaeger on Jun 19, 2019, 15:55

@AKRay93 Can you upload the log-file (e.g. log.txt)?

**Comment by gjaeger** [comment]
@AKRay93 What's the status?

**Comment by AKRay93** [comment]
I will update when I retried it with a new version installed on a linux virtual box!

Gesendet: Montag, 22. Juli 2019 um 07:18 Uhr
Von: "Gregor Jäger" <notifications@github.com>
An: JuPedSim/jpsreport <jpsreport@noreply.github.com>
Cc: AKRay93 <a-k.raytarowski@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [JuPedSim/jpsreport] Err: The trajectory of ped with ID <1> is not continuous. Please modify the trajectory file! (#133)


@AKRay93 What's the status?

**Comment by gjaeger** [comment]
@AKRay93 You will find a suggested solution  in #143. Would you like to test it?

**Comment by chraibi** [comment]
This issue is not related to Windows/linux, but apparently related to using an old version.

Feel free to reopen it if you think there is still a problem.
