### ISSUE TITLE
Windows.: "Cannot open include file: "boost/polygon/xxx.hpp" 

### ISSUE THREAD

**Issue by gintama1227** [JuPedSim/jpsreport#143]
**JuPedSim - JPSreport**

- Current date   :2019/8/9
- Version        :v0.8.4
- Compiler       :MSVC 19.15.26726.0
- Commit hash    :
- Commit date    :
- Branch         : 
- Python         : 

**Describe the bug**
When I built jpsreport in visual studio 2017 in Windows, there are some errors. "Cannot open include file: "boost/polygon/xxx.hpp". However, I have added boost in the project.
Other syntax error as shown in the screenshots.

**Expected behavior**
I hope you can help me solve the problem. Thank you.

**Screenshots**
![image](https://user-images.githubusercontent.com/34682823/62777119-24d62c80-badf-11e9-8ca2-d8d7cf17634f.png)
![image](https://user-images.githubusercontent.com/34682823/62777146-3586a280-badf-11e9-95d3-2f67cff27e8c.png)

**Additional context**

**Comment by gjaeger** [comment]
Do you read the documentation?
- [Quick Start](http://www.jupedsim.org/jpsreport/2016-11-01-quickstart)
- [Requirements](http://www.jupedsim.org/jpsreport/2016-11-03-requirements.html)
- [boost | Getting Started on Windows](https://www.boost.org/doc/libs/1_65_1/more/getting_started/windows.html)

**Comment by gintama1227** [comment]
I read the documents. However, I use windows. So I read the turtorial of windows for jpscore. http://www.jupedsim.org/jpscore/2018-10-21-windows
I follow the steps. I skip 
![image](https://user-images.githubusercontent.com/34682823/62821264-e145f600-bba4-11e9-82e0-8a4b48978c9b.png) this step. And the next step "Updata-Package -reinstall -ProjectName JPSreport" succeed. See the screenshot. 
![image](https://user-images.githubusercontent.com/34682823/62821269-076b9600-bba5-11e9-9a1f-2ab77bcd068d.png)
However, when I try to build solution. It still fails.

**Comment by gintama1227** [comment]
![20190810193616](https://user-images.githubusercontent.com/34682823/62821366-29b1e380-bba6-11e9-830b-77ea1d5b0291.png)

**Comment by gjaeger** [comment]
It seems to me that it is a problem of visual studio 2017.

@xuqiancheng Do you have any ideas?

**Comment by xuqiancheng** [comment]
@gjaeger 
I have compiled jpsreport successfully on windows with VS2017. See #144 
But I still have some problems when the build type is Debug.

@gintama1227 
I suggest that you can check the **Properties of geometrycore-->C/C++-->General-->Additional  Include Directories**, to see if you include the header file of boost library. If not, please include it and try to compile it again.
If it dosen't work, you can try to build boost library by yourself instead of using NuGet. The version of boost I used is 1.67.
You may also have other problems, I think you can find solution in #144 . 
And using **Release** instead of **Debug**.

**Comment by gintama1227** [comment]
Thank you so much. I have compiled jpsreport successfully. @gjaeger  @xuqiancheng 
By the way, if the version of boost is 1.65.1, there are some errors (C2143/C2518) due to the C++11 and C++ 17. 
I try boost 1.67.0 and succeed.

**Comment by gjaeger** [comment]
@gintama1227 Do you compiled the pull request #144 or the proposed course of action of xuqiancheng?

**Comment by gintama1227** [comment]
Yes, I followed #144 . It is a very elaborate method.

**Comment by gjaeger** [comment]
> Yes, I followed #144 . It is a very elaborate method.

We're working on simplifying it. We are dependent on clues. Thank you very much for your feedback.

Be patient. We are scientists and PhD/master students. Therefore, we primarily care about our research and theses.

Can I close this issue?

**Comment by gintama1227** [comment]
Of course, thank you very much.
