### ISSUE TITLE
Method A | flow over time

### ISSUE THREAD

**Issue by gjaeger** [JuPedSim/jpsreport#155]
**JuPedSim - JPSreport**

Version        : 0.8.4
Compiler       : g++ (8.3.0)
Commit hash    : v0.8.3-119-gbc8ced4
Branch         : develop

For Method A ([Zhang](http://hdl.handle.net/2128/4898), p. 48), the flow over time can be calculated as:

<img width="310" alt="eq31" src="https://user-images.githubusercontent.com/7759675/64343178-5a8e0880-cfec-11e9-81cf-8754908ed500.png">

In Method_A.cpp [line 232](https://github.com/JuPedSim/jpsreport/blob/develop/methods/Method_A.cpp#L232), the flow over time `flow rate` is calculated as:
```
double flow_rate=fps*(N2-N1)*1.00/(t_N2-t_N1)
```

Two questions:
1. Why is the framerate `fps` included in the calculation?
2. Why is the numerator multiplied by one?

**Comment by chraibi** [comment]
1. Since `t_N2` and `t_N1` are integers, I assume that they correspond to *frames*.
`flow_rate` is in seconds, hence the multiplication with `fps`.

2. I think someone wanted to force an integer -> double conversion (sounds like a Python 2 trick ^^).

**Comment by gjaeger** [comment]
Thank you. This answers my questions.
