### ISSUE TITLE
Review Methode A

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpsreport#37]
In Gitlab by @chraibi on Feb 22, 2017, 15:11 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpsreport/issues/62)]

Trying to understand this method. 

I think there may be some problems. Please confirm:

- [ ] `XInFrame` in this [line](https://gitlab.version.fz-juelich.de/jupedsim/jpsreport/blob/master/methods/Method_A.cpp#L89)   is calculated but not used.
- [ ] `YInFrame` in this [line](https://gitlab.version.fz-juelich.de/jupedsim/jpsreport/blob/master/methods/Method_A.cpp#L90)   is calculated but not used.
- [ ] performance: too slow?

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Feb 22, 2017, 15:11

marked the task **`XInFrame` in this [line](https://gitlab.version.fz-juelich.de/jupedsim/jpsreport/blob/master/methods/Method_A.cpp#L89)   is calculated by not used.** as completed

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Feb 22, 2017, 15:11

marked the task **`XInFrame` in this [line](https://gitlab.version.fz-juelich.de/jupedsim/jpsreport/blob/master/methods/Method_A.cpp#L89)   is calculated by not used.** as incomplete

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Oct 5, 2017, 16:15

changed the description

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Mar 22, 2018, 18:03

changed the description

**Comment by gjaeger** [comment]
This is to be considered in issue #130
