### ISSUE TITLE
PyQtGraph

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpsreport#47]
In Gitlab by @chraibi on Mar 22, 2018, 11:35 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpsreport/issues/75)]

Plotting hunderts figures with Matplotlib is very slow.

We should try an alternative, like e.g. PyQthraph

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Mar 22, 2018, 11:40

changed the description

**Comment by gjaeger** [comment]
This issue apparently related to using an old version and will be solved by issue #129.

Feel free to reopen it if you think that we have to discuss.
