### ISSUE TITLE
Method D : Voronoi cells for people leaning over obstacles

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpsreport#50]
In Gitlab by @JuleAdrian on May 3, 2018, 17:46 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpsreport/issues/78)]

In my case, some persons are leaning over the obstacles (PIDs 6, 23, 56). The corners of the corresponding Voronoi Cells are marked by green dots. 

*  Case 1:
For PID 23 and 56, the corresponding Voronoi Cells are lying on the other side of the obstacle. However, the Voronoi cells of the neighboring PIDs (e.g. 37, 34, 28, ..) are cut and not elongated towards the obstacle. That means that the presence of PID 23, 56 affects the density of the neighbors.

*  Case 2:
The Coordinate of PID 6 seems to be just within the obstacle. Therefore, no Voronoi cell is created at all. And the Cell of PID 49 is not cut. That means the density of the neighbors is not affected by PID 49.

**Question:**
How can we proceed with this? Is this an issue that needs to be fixed?

![rho_030_c_56_h0.txt_id_1_00208](https://gitlab.version.fz-juelich.de/JuPedSim/jpsreport/uploads/be4a4853351bd6e2768d2b256d92202f/rho_030_c_56_h0.txt_id_1_00208.png)

**Comment by chraibi** [comment]
In Gitlab by @chraibi on May 7, 2018, 17:26

changed the description

**Comment by chraibi** [comment]
In Gitlab by @chraibi on May 7, 2018, 17:27

Jule,​ please upload a zip-file with your ini-, traj- and geo-file.

**Comment by chraibi** [comment]
In Gitlab by @JuleAdrian on May 8, 2018, 09:27

[030_files.zip](https://gitlab.version.fz-juelich.de/JuPedSim/jpsreport/uploads/eb2a96d30547d082299a20800f5f2ad2/030_files.zip)

**Comment by chraibi** [comment]
In Gitlab by @chraibi on May 8, 2018, 20:07

This is a problem that Gregor faced before. 
The boost-function used by `jpsreport` for calculating the overlap of two polygons does not work properly when one polygon is very thin.  This might be the case in your geometry. 


Most of the problems mentioned above can be solved with the following geometry (small modification of yours)

[geo_56_obstacle_01.xml](https://gitlab.version.fz-juelich.de/JuPedSim/jpsreport/uploads/b94a256eb696aa6b9c45338a1398b60f/geo_56_obstacle_01.xml)

![indices](/uploads/07b0b3f8705d414eb959cbc5c5ab96cd/indices.gif)

Pedestrians that pass the exist (e.g number 21),show a not so nicely sliced polygon. However, here I think the abovementioned function does not deliver erroneous results:

## jpsreport

![Screen_Shot_2018-05-08_at_19.54.27](/uploads/78608782823e4ac4ba8e6e4501adda68/Screen_Shot_2018-05-08_at_19.54.27.png)


## debugging the result from boost

![result](/uploads/0009e76d9420cce1b379c6141103c1c0/result.png)

![s](/uploads/b7accb95902a5857c74a2fa97073fed6/s.png)


**What do you think?**

Here is the result of a bend exit

![Screen_Shot_2018-05-08_at_22.07.13](/uploads/80c1fc9847a59d4933dc6aa81a9b9f58/Screen_Shot_2018-05-08_at_22.07.13.png)






@gjaeger

**Comment by chraibi** [comment]
In Gitlab by @gjaeger on May 9, 2018, 08:45

@chraibi 
>  This is a problem that Gregor faced before. 
The boost-function used by `jpsreport` for calculating the overlap of two polygons does not work properly when one polygon is very thin.  This might be the case in your geometry.

Which polygon do you mean? The barrier or the polygon of an agent/ a person?

**Comment by chraibi** [comment]
In Gitlab by @chraibi on May 9, 2018, 08:47

The first polygon is the Voronoi diagram of a pedestrian.
The second polygon is the obstacle.

**Comment by chraibi** [comment]
In Gitlab by @JuleAdrian on May 9, 2018, 10:35

@chraibi 

> Most of the problems mentioned above can be solved with the following geometry (small modification of yours)

In your example video person 13 vanishes in the obstacle. So the problem still exists. 
Would you recommend to edit the trajectories so that all trajectories stay inside the geometry? Even if this means that the marker is located on the back instead of the head..

**Comment by chraibi** [comment]
In Gitlab by @JuleAdrian on May 9, 2018, 10:41

@chraibi 

Here's a plot of the same frame as my first example plot. Now all persons leaning over the barrier vanish inside the obstacle and are not assigned with a voronoi cell. Therefore, they do not contribute to the density measure of the neighboring persons.

![rho_030_c_56_h0.txt_id_3_00208](https://gitlab.version.fz-juelich.de/JuPedSim/jpsreport/uploads/3b6d03e7769ba5a825f34f08f1000709/rho_030_c_56_h0.txt_id_3_00208.png)

**Comment by chraibi** [comment]
In Gitlab by @chraibi on May 9, 2018, 11:51

I see the problem. I would not edit the trajectories and would keep the originals. 

Here the only "parameter" is the geometry. If it does not fit the trajectories, `jpsreport` will chock on it.


![Screen_Shot_2018-05-09_at_11.49.27](https://gitlab.version.fz-juelich.de/JuPedSim/jpsreport/uploads/b19cd7736899ac5a3a7c67e5efcf709c/Screen_Shot_2018-05-09_at_11.49.27.png)
![Screen_Shot_2018-05-09_at_11.49.44](/uploads/5aac4d415c78fa4bf0a98a801aec3a1e/Screen_Shot_2018-05-09_at_11.49.44.png)

**Comment by chraibi** [comment]
In Gitlab by @chraibi on May 9, 2018, 15:47

I just remembered. @gjaeger  and me had once a lousy discussion about how to *automatically* find 
_the_ geometry that fits best the trajectories. 
![Screen_Shot_2018-05-09_at_15.45.55](https://gitlab.version.fz-juelich.de/JuPedSim/jpsreport/uploads/50c0f457c4850ab27738f5f936ed46c3/Screen_Shot_2018-05-09_at_15.45.55.png)

The bad news is I did not manage to finish. The blue points need to be connected. But how? :thinking\_face: 


Here my solution so far as notebook 

[make_geometry.zip](/uploads/6c45ee40ac0e289109aa7ef6254fdeae/make_geometry.zip)

**Comment by chraibi** [comment]
In Gitlab by @gjaeger on May 9, 2018, 16:11

@chraibi That's not the solution for this problem. 

The question is: How can we track/analyze agents who leaning over the barrier?

**Comment by chraibi** [comment]
In Gitlab by @chraibi on May 22, 2018, 14:53

mentioned in commit 0e31449697d0fb41b472220a072e523df588ed37

**Comment by gjaeger** [comment]
solved with pull request #142.
