### ISSUE TITLE
Method I | "isOneDimensional" parameter

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpsreport#72]
In Gitlab by @subaih1 on Apr 12, 2019, 22:01 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpsreport/issues/106)]

In inifile `isOneDimensional` parameter is not work. I get no results

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Apr 13, 2019, 00:02

Please post an inifile, a geometry and a trajectory file. Otherwise, we can not reproduce this bug.

Now that you did not upload the files, I can only guess: 

- this [line](https://gitlab.version.fz-juelich.de/jupedsim/jpsreport/blob/develop/Analysis.cpp#L475) shows that 
`method_I.SetDimensional(_isOneDimensional);` 

However, this may not be executed if you have 0 measurement areas, because of this loop

`
for(long unsigned int i=0; i<_areaForMethod_I.size(); i++)
`

In [this line](https://gitlab.version.fz-juelich.de/jupedsim/jpsreport/blob/develop/methods/Method_I.cpp#L160)

we see that this option, if set to true, should work fine for 1D data.

If method I should not have any measurement areas, then there is no need for that loop.

Please try to fix it by yourself.

**Comment by chraibi** [comment]
In Gitlab by @gjaeger on Jun 14, 2019, 10:23

@subaih1 Does the problem persist?

Can you post an inifile, a geometry and a trajectory file?

**Comment by chraibi** [comment]
In Gitlab by @subaih1 on Jun 28, 2019, 12:40

@gjaeger No it works now

Of course, here is the geometry, inifile, and one of the data files:

[geometry.xml](https://gitlab.version.fz-juelich.de/JuPedSim/jpsreport/uploads/222bfb23dcf595837cbcfcabd82346dc/geometry.xml)

[inifile.xml](/uploads/de66e97036ef0bf08f7a3b1dc5bfc538/inifile.xml)

[UX_14_1.txt](/uploads/0d97e69e03b8321c5bee0d7ab81a9498/UX_14_1.txt)

**Comment by chraibi** [comment]
In Gitlab by @gjaeger on Jun 30, 2019, 14:56

Ok. 

@subaih1 You don't use `one_dimensional enabled="true"` in your inifile.

```xml
    <method_I enabled="true">
        <measurement_area id="1" start_frame="None" stop_frame="None"
                          plot_time_series="false"
                          get_individual_FD="true"/>
        <one_dimensional enabled="false"/>
        <cut_by_circle enabled="true" radius="1.0" edges="10"/>
        <output_voronoi_cells enabled="false" plot_graphs="false"/>
        <profiles enabled="false" grid_size_x="0.20" grid_size_y="0.20"/>
    </method_I>
```

I can't reproduce your problem.

**Comment by gjaeger** [comment]
@rudinamsubaih What's the status?

**Comment by gjaeger** [comment]
This issue apparently related to using an old version.

Feel free to reopen it if you think there is still a problem.
